language: node_js
node_js:
  - '4.2.1'
before_script:
  - npm install -g grunt-cli bower
  - npm install
  - bower install
  - chmod +x ./scripts/deploy.sh
script:
  - ./scripts/deploy.sh
cache:
  directories:
    - node_modules
env:
  global:
    - secure: "lsLjoxU2zXBYDL/pjxvJz89me8aVhGH7ZQldItvh8Nx/+FHDs6MygPA7tIU6Au2P7fJAhwEGPF9g9kn5BHjaoqnv0DfFhlSKJ5vJetwG69PPTXDlTEE17OgDph5D6dEI2BRU2JAZQqps8w4zLm5t7EQMtl89SjqH2/vpc4qT9IQDuTu21HO8I68xPDvW20FnZhIFWS+kWCmiuUI+WD/KY8F9OBupz33ytuv8lo9XtbzMroLQOWoli4OQP1s7zcQb50X+wzyuEOjqV7ZseAfcKBJHRT85Ck252vCOEU+ys/x7w5qYc7P7fpyW+HiVsHdoB2UHL0LBXA7y2BNXcxYN2dh+3JK1mi8ConhMQ61+tEmiKXTivPx4/NXixwPJiev+90URgfbXqyK31at/Yqctm1v/fCielke7IPzxTP7DnNlnM06MheO+LvrWNOvYrUjurbwhpz7NrTdMZYCRqNyfNnBXbD+8GN/NyCaEasrgFdqdvkn+2GPnthiwn9MXb9p1u/hz2GJ7SMlFWXKr1JTthKK2hZ2ffLNmMPu9QhuGQtjH+L1V6Yh/Md8FDuh3d7YVYLlMRKA7XI05a1ZEF74E9mnd/AyTZq4Ub+2dpBQ3rkzYIoMq2dI+ONmco1/lyiXAgIIezR5E7AMY0ZkalZYrAzYxj1fCCVmAlKKxakeYwHs="
